export const colorList = [
  {
    colorGroup: 'XBS 01',
    color: 'White',
    red: 255,
    green: 255,
    blue: 255,
  },
  {
    colorGroup: 'XBS 30',
    color: 'Black',
    red: 0,
    green: 0,
    blue: 0,
  },
  {
    colorGroup: 'Green',
    color: 'Inchworm',
    red: 178,
    green: 236,
    blue: 93,
  },
  {
    colorGroup: 'Green',
    color: 'Lawn Green',
    red: 124,
    green: 252,
    blue: 0,
  },
  {
    colorGroup: 'Green',
    color: 'Bright Green',
    red: 102,
    green: 255,
    blue: 0,
  },
  {
    colorGroup: 'Green',
    color: 'Celadon',
    red: 172,
    green: 225,
    blue: 175,
  },
  {
    colorGroup: 'Green',
    color: 'Pastel Green',
    red: 119,
    green: 221,
    blue: 119,
  },
  {
    colorGroup: 'Green',
    color: 'Pistachio',
    red: 147,
    green: 197,
    blue: 114,
  },
  {
    colorGroup: 'Green',
    color: 'Dollar Bill',
    red: 133,
    green: 187,
    blue: 101,
  },
  {
    colorGroup: 'Green',
    color: 'Asparagus',
    red: 135,
    green: 169,
    blue: 107,
  },
  {
    colorGroup: 'Green',
    color: 'Dark Pastel Green',
    red: 3,
    green: 192,
    blue: 60,
  },
  {
    colorGroup: 'Green',
    color: 'Camouflage Green',
    red: 120,
    green: 134,
    blue: 107,
  },
  {
    colorGroup: 'Green',
    color: 'India Green',
    red: 19,
    green: 136,
    blue: 8,
  },
  {
    colorGroup: 'Green',
    color: 'Green',
    red: 0,
    green: 128,
    blue: 0,
  },
  {
    colorGroup: 'Green',
    color: 'Dark Olive Green',
    red: 85,
    green: 107,
    blue: 47,
  },
  {
    colorGroup: 'Green',
    color: 'Rifle Green',
    red: 65,
    green: 72,
    blue: 51,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Aquamarine',
    red: 127,
    green: 255,
    blue: 212,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Clover',
    red: 0,
    green: 255,
    blue: 111,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Ash Grey',
    red: 178,
    green: 190,
    blue: 181,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Cambridge Blue',
    red: 163,
    green: 193,
    blue: 173,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Caribbean Green',
    red: 0,
    green: 204,
    blue: 153,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Emerald',
    red: 80,
    green: 200,
    blue: 120,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Mint',
    red: 62,
    green: 180,
    blue: 137,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Dark Pastel Green',
    red: 3,
    green: 192,
    blue: 60,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Jade',
    red: 0,
    green: 168,
    blue: 107,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Xanadu',
    red: 115,
    green: 134,
    blue: 120,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Tropical Rain Forest',
    red: 0,
    green: 117,
    blue: 94,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Dark Spring Green',
    red: 23,
    green: 114,
    blue: 69,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Cadmium Green',
    red: 0,
    green: 107,
    blue: 60,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Forest Green',
    red: 1,
    green: 68,
    blue: 33,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'British Racing Green',
    red: 0,
    green: 66,
    blue: 37,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Dark Green',
    red: 1,
    green: 50,
    blue: 32,
  },
  {
    colorGroup: 'Green-Cyan',
    color: 'Dark Jungle Green',
    red: 26,
    green: 36,
    blue: 33,
  },
  {
    colorGroup: 'Cyan',
    color: 'Bubbles',
    red: 231,
    green: 254,
    blue: 255,
  },
  {
    colorGroup: 'Cyan',
    color: 'Cyan',
    red: 0,
    green: 255,
    blue: 255,
  },
  {
    colorGroup: 'Cyan',
    color: 'Columbia Blue',
    red: 155,
    green: 221,
    blue: 255,
  },
  {
    colorGroup: 'Cyan',
    color: 'Bright Turquoise',
    red: 8,
    green: 232,
    blue: 222,
  },
  {
    colorGroup: 'Cyan',
    color: 'Baby Blue',
    red: 137,
    green: 207,
    blue: 240,
  },
  {
    colorGroup: 'Cyan',
    color: 'Sky Blue',
    red: 135,
    green: 206,
    blue: 235,
  },
  {
    colorGroup: 'Cyan',
    color: 'Pastel Blue',
    red: 174,
    green: 198,
    blue: 207,
  },
  {
    colorGroup: 'Cyan',
    color: 'Turquoise',
    red: 48,
    green: 213,
    blue: 200,
  },
  {
    colorGroup: 'Cyan',
    color: 'Dark Cyan',
    red: 0,
    green: 139,
    blue: 139,
  },
  {
    colorGroup: 'Cyan',
    color: 'Cerulean',
    red: 0,
    green: 123,
    blue: 167,
  },
  {
    colorGroup: 'Cyan',
    color: 'Teal',
    red: 0,
    green: 128,
    blue: 128,
  },
  {
    colorGroup: 'Cyan',
    color: 'Pine Green',
    red: 1,
    green: 121,
    blue: 111,
  },
  {
    colorGroup: 'Cyan',
    color: 'Dark Slate Gray',
    red: 47,
    green: 79,
    blue: 79,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Alice Blue',
    red: 240,
    green: 248,
    blue: 255,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Baby Blue Eyes',
    red: 161,
    green: 202,
    blue: 241,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Carolina Blue',
    red: 153,
    green: 186,
    blue: 221,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Iceberg',
    red: 113,
    green: 166,
    blue: 210,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Cornflower Blue',
    red: 100,
    green: 149,
    blue: 237,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Dark Pastel Blue',
    red: 119,
    green: 158,
    blue: 203,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'United Nations Blue',
    red: 91,
    green: 146,
    blue: 229,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Bleu De France',
    red: 49,
    green: 140,
    blue: 231,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Azure',
    red: 0,
    green: 127,
    blue: 255,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Air Force Blue',
    red: 93,
    green: 138,
    blue: 168,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Glaucous',
    red: 96,
    green: 130,
    blue: 182,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Steel Blue',
    red: 70,
    green: 130,
    blue: 180,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Denim',
    red: 21,
    green: 96,
    blue: 189,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Cadet',
    red: 83,
    green: 104,
    blue: 120,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Cobalt',
    red: 0,
    green: 71,
    blue: 171,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Yale Blue',
    red: 15,
    green: 77,
    blue: 146,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Dark Cerulean',
    red: 8,
    green: 69,
    blue: 126,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Charcoal',
    red: 54,
    green: 69,
    blue: 79,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Arsenic',
    red: 59,
    green: 68,
    blue: 75,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Dark Midnight Blue',
    red: 0,
    green: 51,
    blue: 102,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Cool Black',
    red: 0,
    green: 46,
    blue: 99,
  },
  {
    colorGroup: 'Cyan-Blue',
    color: 'Oxford Blue',
    red: 0,
    green: 33,
    blue: 71,
  },
  {
    colorGroup: 'Blue',
    color: 'Ghost White',
    red: 248,
    green: 248,
    blue: 255,
  },
  {
    colorGroup: 'Blue',
    color: 'Lavender Blue',
    red: 204,
    green: 204,
    blue: 255,
  },
  {
    colorGroup: 'Blue',
    color: 'Lavender Gray',
    red: 196,
    green: 195,
    blue: 208,
  },
  {
    colorGroup: 'Blue',
    color: 'Ceil',
    red: 146,
    green: 161,
    blue: 207,
  },
  {
    colorGroup: 'Blue',
    color: 'Cool Grey',
    red: 140,
    green: 146,
    blue: 172,
  },
  {
    colorGroup: 'Blue',
    color: 'Blue',
    red: 0,
    green: 0,
    blue: 255,
  },
  {
    colorGroup: 'Blue',
    color: 'Cerulean Blue',
    red: 42,
    green: 82,
    blue: 190,
  },
  {
    colorGroup: 'Blue',
    color: 'International Klein Blue',
    red: 0,
    green: 47,
    blue: 167,
  },
  {
    colorGroup: 'Blue',
    color: 'Dark Powder Blue',
    red: 0,
    green: 51,
    blue: 153,
  },
  {
    colorGroup: 'Blue',
    color: 'Duke Blue',
    red: 0,
    green: 0,
    blue: 156,
  },
  {
    colorGroup: 'Blue',
    color: 'Ultramarine',
    red: 18,
    green: 10,
    blue: 143,
  },
  {
    colorGroup: 'Blue',
    color: 'Dark Blue',
    red: 0,
    green: 0,
    blue: 139,
  },
  {
    colorGroup: 'Blue',
    color: 'Navy Blue',
    red: 0,
    green: 0,
    blue: 128,
  },
  {
    colorGroup: 'Blue',
    color: 'Midnight Blue',
    red: 25,
    green: 25,
    blue: 112,
  },
  {
    colorGroup: 'Blue',
    color: 'Sapphire',
    red: 8,
    green: 37,
    blue: 103,
  },
  {
    colorGroup: 'Blue',
    color: 'Royal Blue',
    red: 0,
    green: 35,
    blue: 102,
  },
  {
    colorGroup: 'Blue-Magenta',
    color: 'Bright Lavender',
    red: 191,
    green: 148,
    blue: 228,
  },
  {
    colorGroup: 'Blue-Magenta',
    color: 'Lavender',
    red: 181,
    green: 126,
    blue: 220,
  },
  {
    colorGroup: 'Blue-Magenta',
    color: 'Dark Pastel Purple',
    red: 150,
    green: 111,
    blue: 214,
  },
  {
    colorGroup: 'Blue-Magenta',
    color: 'Violet',
    red: 143,
    green: 0,
    blue: 255,
  },
  {
    colorGroup: 'Blue-Magenta',
    color: 'Dark Lavender',
    red: 115,
    green: 79,
    blue: 150,
  },
  {
    colorGroup: 'Blue-Magenta',
    color: 'Purple Heart',
    red: 105,
    green: 53,
    blue: 156,
  },
  {
    colorGroup: 'Magenta',
    color: 'Bright Ube',
    red: 209,
    green: 159,
    blue: 232,
  },
  {
    colorGroup: 'Magenta',
    color: 'Magenta',
    red: 255,
    green: 0,
    blue: 255,
  },
  {
    colorGroup: 'Magenta',
    color: 'Pastel Violet',
    red: 203,
    green: 153,
    blue: 201,
  },
  {
    colorGroup: 'Magenta',
    color: 'Pastel Purple',
    red: 179,
    green: 158,
    blue: 181,
  },
  {
    colorGroup: 'Magenta',
    color: 'Byzantine',
    red: 189,
    green: 51,
    blue: 164,
  },
  {
    colorGroup: 'Magenta',
    color: 'Dark Violet',
    red: 148,
    green: 0,
    blue: 211,
  },
  {
    colorGroup: 'Magenta',
    color: 'Plum',
    red: 142,
    green: 69,
    blue: 133,
  },
  {
    colorGroup: 'Magenta',
    color: 'Dark Magenta',
    red: 139,
    green: 0,
    blue: 139,
  },
  {
    colorGroup: 'Magenta',
    color: 'Byzantium',
    red: 112,
    green: 41,
    blue: 99,
  },
  {
    colorGroup: 'Magenta',
    color: 'Dark Byzantium',
    red: 93,
    green: 57,
    blue: 84,
  },
  {
    colorGroup: 'Magenta-Pink',
    color: 'Lavender Blush',
    red: 255,
    green: 240,
    blue: 245,
  },
  {
    colorGroup: 'Magenta-Pink',
    color: 'Classic Rose',
    red: 251,
    green: 204,
    blue: 231,
  },
  {
    colorGroup: 'Magenta-Pink',
    color: 'Pastel Magenta',
    red: 244,
    green: 154,
    blue: 194,
  },
  {
    colorGroup: 'Magenta-Pink',
    color: 'Sky Magenta',
    red: 207,
    green: 113,
    blue: 175,
  },
  {
    colorGroup: 'Magenta-Pink',
    color: 'Bright Pink',
    red: 255,
    green: 0,
    blue: 127,
  },
  {
    colorGroup: 'Magenta-Pink',
    color: 'Dark Raspberry',
    red: 135,
    green: 38,
    blue: 87,
  },
  {
    colorGroup: 'Magenta-Pink',
    color: 'Eggplant',
    red: 97,
    green: 64,
    blue: 81,
  },
  {
    colorGroup: 'Pink',
    color: 'Pastel Pink',
    red: 255,
    green: 209,
    blue: 220,
  },
  {
    colorGroup: 'Pink',
    color: 'Pink',
    red: 255,
    green: 192,
    blue: 203,
  },
  {
    colorGroup: 'Pink',
    color: 'Cherry Blossom Pink',
    red: 255,
    green: 183,
    blue: 197,
  },
  {
    colorGroup: 'Pink',
    color: 'Flamingo Pink',
    red: 252,
    green: 142,
    blue: 172,
  },
  {
    colorGroup: 'Pink',
    color: 'Dark Pink',
    red: 231,
    green: 84,
    blue: 128,
  },
  {
    colorGroup: 'Pink',
    color: 'Blush',
    red: 222,
    green: 93,
    blue: 131,
  },
  {
    colorGroup: 'Pink',
    color: 'Cherry',
    red: 222,
    green: 49,
    blue: 99,
  },
  {
    colorGroup: 'Pink',
    color: 'Raspberry',
    red: 227,
    green: 11,
    blue: 93,
  },
  {
    colorGroup: 'Pink',
    color: 'Ruby',
    red: 224,
    green: 17,
    blue: 95,
  },
  {
    colorGroup: 'Pink',
    color: 'Bright Maroon',
    red: 195,
    green: 33,
    blue: 72,
  },
  {
    colorGroup: 'Pink',
    color: 'Burgundy',
    red: 128,
    green: 0,
    blue: 32,
  },
  {
    colorGroup: 'Pink',
    color: 'Dark Scarlet',
    red: 86,
    green: 3,
    blue: 25,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Bubble Gum',
    red: 255,
    green: 193,
    blue: 204,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Amaranth',
    red: 229,
    green: 43,
    blue: 80,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Dark Terra Cotta',
    red: 204,
    green: 78,
    blue: 92,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Bazaar',
    red: 152,
    green: 119,
    blue: 123,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Alizarin',
    red: 227,
    green: 38,
    blue: 54,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Crimson',
    red: 220,
    green: 20,
    blue: 60,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Cadmium Red',
    red: 227,
    green: 0,
    blue: 34,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Cardinal',
    red: 196,
    green: 30,
    blue: 58,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Cordovan',
    red: 137,
    green: 63,
    blue: 69,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Carmine',
    red: 150,
    green: 0,
    blue: 24,
  },
  {
    colorGroup: 'Pink-Red',
    color: 'Rosewood',
    red: 101,
    green: 0,
    blue: 11,
  },
  {
    colorGroup: 'Red',
    color: 'Snow',
    red: 255,
    green: 250,
    blue: 250,
  },
  {
    colorGroup: 'Red',
    color: 'Baby Pink',
    red: 244,
    green: 194,
    blue: 194,
  },
  {
    colorGroup: 'Red',
    color: 'Pastel Red',
    red: 255,
    green: 105,
    blue: 97,
  },
  {
    colorGroup: 'Red',
    color: 'Indian Red',
    red: 255,
    green: 92,
    blue: 92,
  },
  {
    colorGroup: 'Red',
    color: 'Ferrari Red',
    red: 255,
    green: 28,
    blue: 0,
  },
  {
    colorGroup: 'Red',
    color: 'Candy Apple Red',
    red: 255,
    green: 8,
    blue: 0,
  },
  {
    colorGroup: 'Red',
    color: 'Red',
    red: 255,
    green: 0,
    blue: 0,
  },
  {
    colorGroup: 'Red',
    color: 'Chestnut',
    red: 205,
    green: 92,
    blue: 92,
  },
  {
    colorGroup: 'Red',
    color: 'Cinnabar',
    red: 227,
    green: 66,
    blue: 52,
  },
  {
    colorGroup: 'Red',
    color: 'Jasper',
    red: 215,
    green: 59,
    blue: 62,
  },
  {
    colorGroup: 'Red',
    color: 'Fire Engine Red',
    red: 206,
    green: 22,
    blue: 32,
  },
  {
    colorGroup: 'Red',
    color: 'Boston University Red',
    red: 204,
    green: 0,
    blue: 0,
  },
  {
    colorGroup: 'Red',
    color: 'Firebrick',
    red: 178,
    green: 34,
    blue: 34,
  },
  {
    colorGroup: 'Red',
    color: 'Cornell Red',
    red: 179,
    green: 27,
    blue: 27,
  },
  {
    colorGroup: 'Red',
    color: 'Dark Candy Apple Red',
    red: 164,
    green: 0,
    blue: 0,
  },
  {
    colorGroup: 'Red',
    color: 'Maroon',
    red: 128,
    green: 0,
    blue: 0,
  },
  {
    colorGroup: 'Red',
    color: 'Prune',
    red: 112,
    green: 28,
    blue: 28,
  },
  {
    colorGroup: 'Red',
    color: 'Dark Sienna',
    red: 60,
    green: 20,
    blue: 20,
  },
  {
    colorGroup: 'Red',
    color: 'Seal Brown',
    red: 50,
    green: 20,
    blue: 20,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Atomic Tangerine',
    red: 255,
    green: 153,
    blue: 102,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Salmon',
    red: 255,
    green: 140,
    blue: 105,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Dark Salmon',
    red: 233,
    green: 150,
    blue: 122,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Coral',
    red: 255,
    green: 127,
    blue: 80,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Burnt Sienna',
    red: 233,
    green: 116,
    blue: 81,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Portland Orange',
    red: 255,
    green: 90,
    blue: 54,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Terra Cotta',
    red: 226,
    green: 114,
    blue: 91,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Coquelicot',
    red: 255,
    green: 56,
    blue: 0,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Flame',
    red: 226,
    green: 88,
    blue: 34,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Cinereous',
    red: 152,
    green: 129,
    blue: 123,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Dark Coral',
    red: 205,
    green: 91,
    blue: 69,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Dark Chestnut',
    red: 152,
    green: 105,
    blue: 96,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Sinopia',
    red: 203,
    green: 65,
    blue: 11,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Dark Pastel Red',
    red: 194,
    green: 59,
    blue: 34,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Mahogany',
    red: 192,
    green: 64,
    blue: 0,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Rust',
    red: 183,
    green: 65,
    blue: 14,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Bole',
    red: 121,
    green: 68,
    blue: 59,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Burnt Umber',
    red: 138,
    green: 51,
    blue: 36,
  },
  {
    colorGroup: 'XBS 26',
    color: 'Auburn',
    red: 109,
    green: 53,
    blue: 26,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Seashell',
    red: 255,
    green: 245,
    blue: 238,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Champagne',
    red: 247,
    green: 231,
    blue: 206,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Peach',
    red: 255,
    green: 229,
    blue: 180,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Wheat',
    red: 245,
    green: 222,
    blue: 179,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Sunset',
    red: 250,
    green: 214,
    blue: 165,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Apricot',
    red: 251,
    green: 206,
    blue: 177,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Desert Sand',
    red: 237,
    green: 201,
    blue: 175,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Pastel Orange',
    red: 255,
    green: 179,
    blue: 71,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Burlywood',
    red: 222,
    green: 184,
    blue: 135,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Dark Tangerine',
    red: 255,
    green: 168,
    blue: 18,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Chrome Yellow',
    red: 255,
    green: 167,
    blue: 0,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Fawn',
    red: 229,
    green: 170,
    blue: 112,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Earth Yellow',
    red: 225,
    green: 169,
    blue: 95,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Indian Yellow',
    red: 227,
    green: 168,
    blue: 87,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Khaki',
    red: 195,
    green: 176,
    blue: 145,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Dark Orange',
    red: 255,
    green: 140,
    blue: 0,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Gamboge',
    red: 228,
    green: 155,
    blue: 15,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Carrot Orange',
    red: 237,
    green: 145,
    blue: 33,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Orange',
    red: 255,
    green: 127,
    blue: 0,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Tangerine',
    red: 242,
    green: 133,
    blue: 0,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Cadmium Orange',
    red: 237,
    green: 135,
    blue: 45,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Pumpkin',
    red: 255,
    green: 117,
    blue: 24,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Desert',
    red: 193,
    green: 154,
    blue: 107,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Safety Orange',
    red: 255,
    green: 103,
    blue: 0,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Bronze',
    red: 205,
    green: 127,
    blue: 50,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Ochre',
    red: 204,
    green: 119,
    blue: 34,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Cinnamon',
    red: 210,
    green: 105,
    blue: 30,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Copper',
    red: 184,
    green: 115,
    blue: 51,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Chamoisee',
    red: 160,
    green: 120,
    blue: 90,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Burnt Orange',
    red: 204,
    green: 85,
    blue: 0,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Shadow',
    red: 138,
    green: 121,
    blue: 93,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Golden Brown',
    red: 153,
    green: 101,
    blue: 21,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Pastel Brown',
    red: 131,
    green: 105,
    blue: 83,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Raw Umber',
    red: 130,
    green: 102,
    blue: 68,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Brown',
    red: 150,
    green: 75,
    blue: 0,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Chocolate',
    red: 123,
    green: 63,
    blue: 0,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Sepia',
    red: 112,
    green: 66,
    blue: 20,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Dark Brown',
    red: 101,
    green: 67,
    blue: 33,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Dark Lava',
    red: 72,
    green: 60,
    blue: 50,
  },
  {
    colorGroup: 'XBS 25',
    color: 'Bistre',
    red: 61,
    green: 43,
    blue: 31,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Cornsilk',
    red: 255,
    green: 248,
    blue: 220,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Blond',
    red: 250,
    green: 240,
    blue: 190,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Pearl',
    red: 240,
    green: 234,
    blue: 214,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Platinum',
    red: 229,
    green: 228,
    blue: 226,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Vanilla',
    red: 243,
    green: 229,
    blue: 171,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Mustard',
    red: 255,
    green: 219,
    blue: 88,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Buff',
    red: 240,
    green: 220,
    blue: 130,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Banana Yellow',
    red: 255,
    green: 209,
    blue: 42,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Arylide Yellow',
    red: 233,
    green: 214,
    blue: 107,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Saffron',
    red: 244,
    green: 196,
    blue: 48,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Amber',
    red: 255,
    green: 191,
    blue: 0,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Sand',
    red: 194,
    green: 178,
    blue: 128,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Goldenrod',
    red: 218,
    green: 165,
    blue: 32,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Dark Goldenrod',
    red: 184,
    green: 134,
    blue: 11,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Dark Tan',
    red: 145,
    green: 129,
    blue: 81,
  },
  {
    colorGroup: 'Orange-Yellow',
    color: 'Sand Dune',
    red: 150,
    green: 113,
    blue: 23,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Ivory',
    red: 255,
    green: 255,
    blue: 240,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Cream',
    red: 255,
    green: 253,
    blue: 208,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Pastel Yellow',
    red: 253,
    green: 253,
    blue: 150,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Beige',
    red: 245,
    green: 245,
    blue: 220,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Daffodil',
    red: 255,
    green: 255,
    blue: 49,
  },
  {
    colorGroup: 'XBS 21',
    color: 'XBS 21',
    red: 255,
    green: 255,
    blue: 0,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Icterine',
    red: 252,
    green: 247,
    blue: 94,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Lemon',
    red: 255,
    green: 247,
    blue: 0,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Canary Yellow',
    red: 255,
    green: 239,
    blue: 0,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Flavescent',
    red: 247,
    green: 233,
    blue: 142,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Corn',
    red: 251,
    green: 236,
    blue: 93,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Golden Yellow',
    red: 255,
    green: 223,
    blue: 0,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Titanium Yellow',
    red: 238,
    green: 230,
    blue: 0,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Dandelion',
    red: 240,
    green: 225,
    blue: 48,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Peridot',
    red: 230,
    green: 226,
    blue: 0,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Straw',
    red: 228,
    green: 217,
    blue: 111,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Sandstorm',
    red: 236,
    green: 213,
    blue: 64,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Pastel Gray',
    red: 207,
    green: 207,
    blue: 196,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Citrine',
    red: 228,
    green: 208,
    blue: 10,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Dark Khaki',
    red: 189,
    green: 183,
    blue: 107,
  },
  {
    colorGroup: 'XBS 21',
    color: 'Brass',
    red: 181,
    green: 166,
    blue: 66,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Chartreuse',
    red: 223,
    green: 255,
    blue: 0,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Lime',
    red: 191,
    green: 255,
    blue: 0,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Spring Bud',
    red: 167,
    green: 252,
    blue: 0,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Pear',
    red: 209,
    green: 226,
    blue: 49,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Android Green',
    red: 164,
    green: 198,
    blue: 57,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Apple Green',
    red: 141,
    green: 182,
    blue: 0,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Battleship Grey',
    red: 132,
    green: 132,
    blue: 130,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Olive',
    red: 128,
    green: 128,
    blue: 0,
  },
  {
    colorGroup: 'XBS 04',
    color: 'Army Green',
    red: 75,
    green: 83,
    blue: 32,
  },
  // Digital color
  {
    colorGroup: 'XBS 01',
    color: 'XBS 01',
    red: 220,
    green: 225,
    blue: 228,
  },
  {
    colorGroup: 'XBS 02',
    color: 'XBS 02',
    red: 215,
    green: 212,
    blue: 197,
  },
  {
    colorGroup: 'XBS 03',
    color: 'XBS 03',
    red: 130,
    green: 131,
    blue: 125,
  },
  {
    colorGroup: 'XBS 04',
    color: 'XBS 04',
    red: 92,
    green: 92,
    blue: 91,
  },
  {
    colorGroup: 'XBS 05',
    color: 'XBS 05',
    red: 133,
    green: 125,
    blue: 114,
  },
  {
    colorGroup: 'XBS 06',
    color: 'XBS 06',
    red: 120,
    green: 116,
    blue: 112,
  },
  {
    colorGroup: 'XBS 08',
    color: 'XBS 08',
    red: 86,
    green: 85,
    blue: 84,
  },
  {
    colorGroup: 'XBS 10',
    color: 'XBS 10',
    red: 65,
    green: 70,
    blue: 70,
  },
  {
    colorGroup: 'XBS 13',
    color: 'XBS 13',
    red: 194,
    green: 177,
    blue: 154,
  },
  {
    colorGroup: 'XBS 15',
    color: 'XBS 15',
    red: 191,
    green: 177,
    blue: 161,
  },
  {
    colorGroup: 'XBS 16',
    color: 'XBS 16',
    red: 155,
    green: 138,
    blue: 123,
  },
  {
    colorGroup: 'XBS 17',
    color: 'XBS 17',
    red: 173,
    green: 144,
    blue: 127,
  },
  {
    colorGroup: 'XBS 19',
    color: 'XBS 19',
    red: 214,
    green: 197,
    blue: 149,
  },
  {
    colorGroup: 'XBS 21',
    color: 'XBS 21',
    red: 196,
    green: 172,
    blue: 113,
  },
  {
    colorGroup: 'XBS 25',
    color: 'XBS 25',
    red: 133,
    green: 103,
    blue: 87,
  },
  {
    colorGroup: 'XBS 26',
    color: 'XBS 26',
    red: 141,
    green: 93,
    blue: 73,
  },
  {
    colorGroup: 'XBS 28',
    color: 'XBS 28',
    red: 137,
    green: 110,
    blue: 83,
  },
  {
    colorGroup: 'XBS 29',
    color: 'XBS 29',
    red: 148,
    green: 130,
    blue: 100,
  },
  {
    colorGroup: 'XBS 30',
    color: 'XBS 30',
    red: 41,
    green: 43,
    blue: 47,
  },
  {
    colorGroup: 'XBS 31',
    color: 'XBS 31',
    red: 216,
    green: 171,
    blue: 70,
  },
  {
    colorGroup: 'XBS 32',
    color: 'XBS 32',
    red: 213,
    green: 215,
    blue: 207,
  },
  {
    colorGroup: 'XBS 33',
    color: 'XBS 33',
    red: 183,
    green: 131,
    blue: 35,
  },
  {
    colorGroup: 'XBS 34',
    color: 'XBS 34',
    red: 227,
    green: 228,
    blue: 222,
  },
  {
    colorGroup: 'XBS 35',
    color: 'XBS 35',
    red: 156,
    green: 152,
    blue: 146,
  },
  {
    colorGroup: 'XBS 36',
    color: 'XBS 36',
    red: 115,
    green: 100,
    blue: 84,
  },
  {
    colorGroup: 'XBS 37',
    color: 'XBS 37',
    red: 207,
    green: 179,
    blue: 124,
  },
  {
    colorGroup: 'XBS 38',
    color: 'XBS 38',
    red: 156,
    green: 150,
    blue: 146,
  },
  {
    colorGroup: 'XBS 39',
    color: 'XBS 39',
    red: 186,
    green: 135,
    blue: 107,
  },
  {
    colorGroup: 'XBS 40',
    color: 'XBS 40',
    red: 183,
    green: 184,
    blue: 177,
  },
  {
    colorGroup: 'XBS 41',
    color: 'XBS 41',
    red: 173,
    green: 175,
    blue: 174,
  },
  {
    colorGroup: 'XBS 42',
    color: 'XBS 42',
    red: 124,
    green: 130,
    blue: 128,
  },
];
